### ISSUE TITLE
Spark 1.6.1

### ISSUE THREAD

**Issue by DarkBlaez** [metreta/spark-orientdb-connector#5]
Is there a Spark 1.6.1 version of the connector? In the branches I see variations but nothing with the current version. I have modified build.sbt to pick up the versions for Spark 1.6.1 as well as the OrientDB version I am running 2.1.15

**build.sbt:**
lazy val commonSettings = Seq(
  organization := "com.metreta",
  version := "v1.6-2.10",
  scalaVersion := "2.10.5",
  fork:= true,
  libraryDependencies ++= Seq(
    "com.orientechnologies" % "orientdb-core" % "2.1.15",
    "com.orientechnologies" % "orientdb-client" % "2.1.15",
    "com.orientechnologies" % "orientdb-jdbc" % "2.1.15",
    "com.orientechnologies" % "orientdb-graphdb" % "2.1.15",
    "com.orientechnologies" % "orientdb-distributed" % "2.1.15",
    "org.scalatest" % "scalatest_2.10" % "2.2.4",
    "org.apache.spark" % "spark-core_2.10" % "1.6.1",
    "org.apache.spark" % "spark-graphx_2.10" % "1.6.1",
    "com.tinkerpop.blueprints" % "blueprints-core" % "2.6.0"
    ),
    externalResolvers := Seq(DefaultMavenRepository)
)

lazy val connector = (project in file("./spark-orientdb-connector")).
  settings(commonSettings: _*).
  settings(
    name := "spark-orientdb-connector"
    )

lazy val demos = (project in file("./spark-orientdb-connector-demos")).
  settings(commonSettings: _*).
  settings(
    name := "spark-orientdb-connector-demos"
    ).
   dependsOn(connector)

Yet when tested in spark-shell an error is thrown:
**scala>**
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext
import com.metreta.spark.orientdb.connector._

val conf = new SparkConf()

**Exception Thrown:**
error: bad symbolic reference. A signature in package.class refers to term orientechnologies
in package com which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling package.class.
error: bad symbolic reference. A signature in package.class refers to term orient
in value com.orientechnologies which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling package.class.
error: bad symbolic reference. A signature in package.class refers to term core
in value com.orient which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling package.class.
error: bad symbolic reference. A signature in package.class refers to term metadata
in value com.core which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling package.class.
<console>:30: error: bad symbolic reference. A signature in package.class refers to term schema
in value com.metadata which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling package.class.
         val conf = new SparkConf()

**Comment by vzamboni** [comment]
In the next week we expect to release the Spark 1.6.1 version of the connector. stay tuned!

**Comment by vzamboni** [comment]
New tags added:

- 1.6-beta-1-2.10 compiled with scala 2.10 and spark 1.6.0
- 1.6-beta-1-2.11 compiled with scala 2.11 and spark 1.6.0

check [version list](https://github.com/metreta/spark-orientdb-connector/blob/master/docs/version_list.md)
